[project]
name = "tghtml"
version = "2.0.1"
description = "Simple tool for parse common HTML to Telegram HTML"
authors = [{ name = "Daniel Zakharov", email = "gzdan734@gmail.com" }]
requires-python = ">=3.10,<4"
license = "MIT"
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
    "haitch>=0.15.0",
    "nh3>=0.3.4",
    "pylatexenc>=2.10",
    "selectolax>=0.4.7",
]

[tool.uv.build-backend]
module-root = ""

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
tghtml = { workspace = true }

[build-system]
requires = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "tghtml",
]

[tool.ruff]
line-length = 80
